version: "3.9"

services:
  # Financial Agentic Project Services
  langgraph-agents:
    build: ./langgraph-agents
    ports:
      - "5001:5000"
    environment:
      # Memory Services
      REDIS_URL: ${REDIS_URL:-redis://financial-redis:6379/0}
      QDRANT_HOST: ${QDRANT_HOST:-financial-qdrant}
      QDRANT_PORT: ${QDRANT_PORT:-6333}
      # MCP Tools
      MCP_BASE_URL: ${MCP_BASE_URL:-http://mcp-finance-tools:4000}
      # Hugging Face API
      HUGGINGFACE_API_URL: ${HUGGINGFACE_API_URL:-https://router.huggingface.co/novita/v3/openai/chat/completions}
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
      HUGGINGFACE_MODEL: ${HUGGINGFACE_MODEL:-deepseek/deepseek-v3-0324}
      # Kafka Integration
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-financial-kafka:9092}
      # Ollama Integration
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://financial-ollama:11434}
      # Flask Configuration
      FLASK_HOST: ${FLASK_HOST:-0.0.0.0}
      FLASK_PORT: ${FLASK_PORT:-5000}
      FLASK_DEBUG: ${FLASK_DEBUG:-false}
      # CORS Configuration
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000}
    depends_on:
      - financial-redis
      - financial-qdrant
      - mcp-finance-tools
      - financial-kafka
      - financial-ollama
    networks:
      - financial-network

  mcp-finance-tools:
    build: ./mcp-finance-tools
    ports:
      - "4000:4000"
    networks:
      - financial-network

  web-ui:
    build: ./web-ui
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5001}
      NEXT_PUBLIC_STREAM_URL: ${NEXT_PUBLIC_STREAM_URL:-http://localhost:5001/stream}
    networks:
      - financial-network

  # External Infrastructure Services (using existing containers)
  financial-redis:
    image: redis:7-alpine
    container_name: financial-redis
    ports:
      - "6379:6379"
    networks:
      - financial-network

  financial-qdrant:
    image: qdrant/qdrant:latest
    container_name: financial-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - financial-network

  financial-kafka:
    image: bitnami/kafka:3.4
    container_name: financial-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: financial-zookeeper:2181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://financial-kafka:9092
    networks:
      - financial-network

  financial-zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: financial-zookeeper
    ports:
      - "2181:2181"
    networks:
      - financial-network

  financial-ollama:
    image: ollama/ollama:latest
    container_name: financial-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - financial-network


volumes:
  qdrant_data:
  ollama_data:

networks:
  financial-network:
    driver: bridge
